server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 30000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

jwt:
  secret: "RGlydHlBbGV4U3VwZXJTZWNyZXRQYXNzd29yZDExMTAyMDAy"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha